apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-app
spec:
  replicas: 1   # optional (HPA will override)
  selector:
    matchLabels:
      app: blog-app
  template:
    metadata:
      labels:
        app: blog-app
    spec:
      containers:
      - name: blog-app
        image: thanushdev01/blog-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        resources:
          requests:
            cpu: "100m"        # ✅ REQUIRED for HPA
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
