apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-app
spec:
  replicas: 1   # HPA will override this
  revisionHistoryLimit: 2   # ✅ KEEP ONLY 2 REPLICASETS

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: blog-app

  template:
    metadata:
      labels:
        app: blog-app
    spec:
      containers:
      - name: blog-app
        image: thanushdev01/blog-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
